config/routes.rb
Rails.application.routes.draw do

  root to: 'restaurants#index'

     resources :restaurants do
       resources :reviews, only: [:new, :create]
     end

     resources :restaurants, only: [:new, :create, :index, :show]

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews

  validates_presence_of :name
  validates_presence_of :address
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zip
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  #validates_presence_of :restuarant_id

  validates_presence_of :rating


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    id = params[:id]
    @restaurant = Restaurant.find(id)
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zip)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant_id = @restaurant.id
    if @review.save
      redirect_to @restaurant, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <a href = "<%= restaurants_path %>"><h1>ALL THE RESTAURANTS</h1></a>
  <a href="<%= new_restaurant_path %>"><h2>New Restaurant<h2></a>

  <% if notice %>
    <p><%= notice %></p>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<ul>
<% @restaurants.each do |r| %>
  <li><%= link_to "#{r.name}", restaurant_path(r.id), action: "show" %></li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<%= form_for(@restaurant) do |f| %>
<% if @restaurant.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this from being saved:</h2>

  <ul>
    <% @restaurant.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :address %><br>
  <%= f.text_area :address %>
</div>

<div class="field">
  <%= f.label :city %><br>
  <%= f.text_area :city %>
</div>

<div class="field">
  <%= f.label :state %><br>
  <%= f.text_area :state %>
</div>

<div class="field">
  <%= f.label :zip %><br>
  <%= f.text_area :zip %>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<ul>
  <li>Address: <%= @restaurant.address %></li>
  <li>City: <%= @restaurant.city %></li>
  <li>State: <%= @restaurant.state %></li>
  <li>Zip: <%= @restaurant.zip %></li>
</ul>

<%= link_to "Review this", new_restaurant_review_path(@restaurant.id) %>

<h3>Reviews</h3>

<ul>
  <% @restaurant.reviews.each do |r| %>
    <li>Rating: <%= r.rating %>
      <% if r.comment != "" %>
       | Comment: <%= r.comment %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
<% if @review.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@review.errors.count, "error") %> prohibited this from being saved:</h2>

  <ul>
    <% @review.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :comment %><br>
  <%= f.text_field :comment %>
</div>

<div class="field">
  <%= f.label :rating %><br>
  <% [1,2,3,4,5].each do |rating| %>
  <%= f.radio_button :rating, rating %>
  <%= f.label :rating, rating, value: rating %>
  <% end %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

<% end %>